### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [steelsleuth/EmThreat#56]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by steelsleuth** [comment]
This project stems from a University paper and is modeled on PhishTank's data. PhishTank allows the commercial and non-commercial use of their data.

As support for more datasets are added, each sources terms of service will be considered. The good thing is at least generic file formats can be used. 

A  Unlicense License has been added to the project.
